# -*- coding: utf-8 -*-
"""Cópia de Cópia de SantanderDevWeek2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r3gQ5a-P5I3CjJXJqtjNJbQbjXTKfTif

# Victor Hedlund de Bona - ETL com Python

## **E**xtract

Extraia a lista de IDs de usuário a partir do arquivo CSV. Para cada ID, faça uma requisição GET para obter os dados do usuário correspondente.
"""

import pandas as pd

df = pd.read_csv('Pipeline.csv')
produtos = df['Produto'].tolist()
print(produtos)

display(df)

"""## **T**ransform

Utilize a API do OpenAI GPT-4 para gerar uma mensagem de marketing personalizada para cada usuário.
"""

pricing = []
def generate_value(Produto):
  global valor
  valor = int(input(f"Insira o preço do {Produto}: R$"))
  return valor

for produto in produtos:
  value = generate_value(produto)
  pricing.append(valor)

df['Preço'] = pricing
print(df)

"""## **L**oad

Atualize a lista de "news" de cada usuário na API com a nova mensagem gerada.
"""

def update_product(valor):
  response = df.to_csv('teste.csv')

update_product(valor)

teste = pd.read_csv('teste.csv')
print(teste)